In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv("C:\\Users\\Shubhi\\MACHINE LEARNING\\diabetes.csv")


In [4]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [5]:
df = df.drop("Pregnancies", axis=1)

In [6]:
df.head()


,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,148,72,35,0,33.6,0.627,50,1
1,85,66,29,0,26.6,0.351,31,0
2,183,64,0,0,23.3,0.672,32,1
3,89,66,23,94,28.1,0.167,21,0
4,137,40,35,168,43.1,2.288,33,1


In [7]:
import matplotlib.pyplot as plt

In [8]:
import sklearn
print(sklearn.__version__)

1.8.0


In [9]:
X= df.iloc[: ,0:7]
Y= df.iloc[: ,-1]

In [10]:
X

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,148,72,35,0,33.6,0.627,50
1,85,66,29,0,26.6,0.351,31
2,183,64,0,0,23.3,0.672,32
3,89,66,23,94,28.1,0.167,21
4,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...
763,101,76,48,180,32.9,0.171,63
764,122,70,27,0,36.8,0.340,27
765,121,72,23,112,26.2,0.245,30
766,126,60,0,0,30.1,0.349,47


In [11]:
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [12]:
X.shape

(768, 7)

In [13]:
Y.shape

(768,)

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.2)

In [15]:
X_train

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
606,181,78,42,293,40.0,1.258,22
463,88,78,30,0,27.6,0.258,37
390,100,66,29,196,32.0,0.444,42
382,109,60,8,182,25.4,0.947,21
122,107,74,30,100,33.6,0.404,23
...,...,...,...,...,...,...,...
758,106,76,0,0,37.5,0.197,26
674,91,82,0,0,35.6,0.587,68
607,92,62,25,41,19.5,0.482,25
329,105,70,32,68,30.8,0.122,37


In [16]:
Y_train

606    1
463    0
390    0
382    0
122    0
      ..
758    0
674    0
607    0
329    0
303    1
Name: Outcome, Length: 614, dtype: int64

In [17]:
X_test

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
383,90,62,18,59,25.1,1.268,25
155,152,88,44,0,50.0,0.337,36
300,167,0,0,0,32.3,0.839,30
490,83,65,28,66,36.8,0.629,24
759,190,92,0,0,35.5,0.278,66
...,...,...,...,...,...,...,...
96,92,62,28,0,31.6,0.130,24
195,158,84,41,210,39.4,0.395,29
560,125,76,0,0,33.8,0.121,54
641,128,70,0,0,34.3,0.303,24


In [18]:
Y_test

383    0
155    1
300    1
490    0
759    1
      ..
96     0
195    1
560    1
641    0
639    0
Name: Outcome, Length: 154, dtype: int64

In [19]:
from sklearn.preprocessing import StandardScaler



In [20]:
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)

In [21]:
X_train

array([[ 1.89543409,  0.43899846,  1.38014285, ...,  1.00679823,
         2.45918414, -0.95526842],
       [-1.04081499,  0.43899846,  0.61000558, ..., -0.57714999,
        -0.66590317,  0.29144012],
       [-0.66194414, -0.1755827 ,  0.54582747, ..., -0.01510385,
        -0.08463693,  0.70700963],
       ...,
       [-0.91452471, -0.38044309,  0.28911505, ..., -1.61182584,
         0.03411638, -0.70592671],
       [-0.50408129,  0.02927769,  0.73836179, ..., -0.16838916,
        -1.09091505,  0.29144012],
       [-0.18835558,  1.4633004 , -1.3153376 , ...,  2.65461533,
        -0.81903245, -0.45658501]], shape=(614, 7))

In [45]:
X_test= scaler.transform(X_test)

C:\Users\Shubhi\anaconda3\envs\new_environment\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [46]:
X_test

array([[ -3.76197907,  -3.85552938,  -1.26609947, ...,  -4.40549436,
         10.67865613,  -3.36622245],
       [ -3.7602598 ,  -3.85145141,  -1.26108017, ...,  -4.35789922,
         -7.38473981,  -3.35673791],
       [ -3.75984385,  -3.86525377,  -1.26957437, ...,  -4.39173191,
          2.35513641,  -3.3619113 ],
       ...,
       [ -3.76100852,  -3.85333355,  -1.26957437, ...,  -4.38886473,
        -11.57560288,  -3.34121775],
       [ -3.76092533,  -3.85427462,  -1.26957437, ...,  -4.38790901,
         -8.0444127 ,  -3.36708468],
       [ -3.76170177,  -3.85364724,  -1.26725777, ...,  -4.41619849,
        -11.03234285,  -3.36363576]], shape=(154, 7))

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
clf= LogisticRegression()

In [49]:
clf.fit(X_train, Y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [50]:
clf.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
from sklearn.metrics import accuracy_score

In [52]:
Y_pred = clf.predict(X_test)
accuracy_score(Y_test, Y_pred)

0.6753246753246753

In [54]:
import pickle
pickle.dump(clf, open('model1.pkl', 'wb'))

In [55]:
print(clf.predict_proba(sample_scaled))

NameError: name 'sample_scaled' is not defined

In [56]:
print(clf.predict_proba(X_test))

[[9.96337825e-01 3.66217525e-03]
 [9.99963016e-01 3.69841831e-05]
 [9.99559470e-01 4.40530109e-04]
 [9.99845179e-01 1.54821441e-04]
 [9.99972708e-01 2.72924520e-05]
 [9.99205778e-01 7.94221698e-04]
 [9.99976900e-01 2.30997052e-05]
 [9.99982611e-01 1.73885303e-05]
 [9.99986115e-01 1.38854339e-05]
 [9.99942400e-01 5.76002569e-05]
 [9.99526978e-01 4.73021899e-04]
 [9.99175539e-01 8.24461036e-04]
 [9.99935607e-01 6.43927599e-05]
 [9.99946696e-01 5.33038245e-05]
 [9.99963603e-01 3.63967744e-05]
 [9.99578398e-01 4.21601733e-04]
 [9.99972869e-01 2.71312398e-05]
 [9.99912680e-01 8.73196613e-05]
 [9.99898647e-01 1.01352666e-04]
 [9.99984674e-01 1.53257102e-05]
 [9.99965557e-01 3.44434057e-05]
 [9.99968735e-01 3.12648639e-05]
 [9.99958978e-01 4.10219759e-05]
 [9.93209531e-01 6.79046858e-03]
 [9.99867497e-01 1.32502539e-04]
 [9.99987071e-01 1.29293113e-05]
 [9.99909180e-01 9.08200675e-05]
 [9.99974139e-01 2.58609848e-05]
 [9.89714882e-01 1.02851184e-02]
 [9.99829415e-01 1.70585136e-04]
 [9.999634

In [57]:
scaler = pickle.load(open('scaler.pkl', 'rb'))

FileNotFoundError: [Errno 2] No such file or directory: 'scaler.pkl'

In [58]:
pickle.dump(scaler, open('scaler.pkl', 'wb'))